version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: chopan_ai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/chopan_ai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services:/app/services
      - ./config:/app/config
    command: uvicorn services.api_gateway.main:app --host 0.0.0.0 --port 8000 --reload

  content-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/chopan_ai
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services:/app/services
      - ./config:/app/config
    command: uvicorn services.content.main:app --host 0.0.0.0 --port 8001 --reload

  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/chopan_ai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services:/app/services
      - ./config:/app/config
    command: uvicorn services.email.main:app --host 0.0.0.0 --port 8002 --reload

  social-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/chopan_ai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services:/app/services
      - ./config:/app/config
    command: uvicorn services.social.main:app --host 0.0.0.0 --port 8003 --reload

  prospect-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/chopan_ai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services:/app/services
      - ./config:/app/config
    command: uvicorn services.prospect.main:app --host 0.0.0.0 --port 8004 --reload

volumes:
  postgres_data:
  redis_data: